versioning:
  major: 1
  minor: 1

cff_config:
  enable_cff_real_h: True
  enable_cff_imag_h: True
  enable_cff_real_e: False
  enable_cff_imag_e: False
  enable_cff_real_ht: True
  enable_cff_imag_ht: True
  enable_cff_real_et: False
  enable_cff_imag_et: False

data_config:
  start_value_of_phi_in_degrees: 0
  end_value_of_phi_in_degrees: 360
  number_of_phi_points: 360

dnn_config:
  epochs: 750
  replicas: 1
  batch_size: 50
  adam_learning_rate: 0.001

observable_config:
  enable_unp_beam_unp_target_xsec: True
  enable_plus_beam_unp_target_xsec: False
  enable_minus_beam_unp_target_xsec: False
  enable_unp_beam_lp_target_xsec: False
  enable_plus_beam_lp_target_xsec: False
  enable_minus_beam_lp_target_xsec: False
  enable_unp_target_bsa: True
  enable_plus_target_bsa: False
  enable_minus_target_bsa: False
  enable_unp_beam_tsa: False
  enable_plus_beam_tsa: False
  enable_minus_beam_tsa: False
  enable_dsa: False