versioning:
  major: 1
  minor: 2

cff_config:
  enable_cff_real_h: True
  enable_cff_imag_h: True
  enable_cff_real_e: True
  enable_cff_imag_e: True
  enable_cff_real_ht: False
  enable_cff_imag_ht: False
  enable_cff_real_et: False
  enable_cff_imag_et: False

dnn_config:
  epochs: 750
  replicas: 1
  batch_size: 50
  adam_learning_rate: 0.001

observable_config:
  enable_unp_beam_unp_target_xsec: True
  enable_plus_beam_unp_target_xsec: False
  enable_minus_beam_unp_target_xsec: False
  enable_unp_beam_lp_target_xsec: False
  enable_plus_beam_lp_target_xsec: False
  enable_minus_beam_lp_target_xsec: False
  enable_unp_target_bsa: True
  enable_plus_target_bsa: False
  enable_minus_target_bsa: False
  enable_unp_beam_tsa: False
  enable_plus_beam_tsa: False
  enable_minus_beam_tsa: False
  enable_dsa: False